import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  projectsSidebar: [
    {
      type: 'category',
      label: 'Infrastructure',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'infrastructure'}],
    },
    {
      type: 'category',
      label: 'AI Factory',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'dhg-ai-factory'}],
    },
    {
      type: 'category',
      label: 'Memreg',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'dhg-memreg'}],
    },
    {
      type: 'category',
      label: 'Memory Pipeline',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'memory-pipeline'}],
    },
    {
      type: 'category',
      label: 'Open WebUI',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'open-webui'}],
    },
    {
      type: 'category',
      label: 'Portage',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'portage'}],
    },
  ],
};

export default sidebars;
