import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  aiFactorySidebar: [
    'getting-started',
    'architecture',
    'services',
    'key-files',
    {
      type: 'category',
      label: 'Ship Log',
      items: [
        {type: 'autogenerated', dirName: 'ship-log'},
      ],
    },
  ],
};

export default sidebars;
