import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  portageSidebar: [
    'getting-started',
    'features',
    'competitive-analysis',
    'environment-variables',
    'deployment',
    'monitoring',
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/database',
        'architecture/ai-pipeline',
        'architecture/marketplace-adapters',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/overview',
        'api/authentication',
        'api/items',
        'api/listings',
        'api/orders',
        'api/scan',
        'api/images',
        'api/marketplace',
        'api/shipping',
        'api/drafts',
        'api/porter',
        'api/admin',
        'api/billing',
        'api/error-handling',
      ],
    },
    {
      type: 'category',
      label: 'Frontend',
      items: [
        'frontend/app-structure',
        'frontend/design-system',
        'frontend/listing-flow',
        'frontend/scan-flow',
      ],
    },
    {
      type: 'category',
      label: 'Design',
      items: [
        'design/style-guide',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'development/history',
        'development/memory-system',
      ],
    },
    {
      type: 'category',
      label: 'Team Process',
      items: [
        'team-process/outcomes-study',
      ],
    },
    {
      type: 'category',
      label: 'Ship Log',
      link: {type: 'doc', id: 'ship-log/index'},
      items: [
        {type: 'autogenerated', dirName: 'ship-log'},
      ],
    },
  ],
};

export default sidebars;
