#!/usr/bin/env bash
# Render observability/postgres-exporter/postgres_exporter.yml from Doppler.
#
# postgres_exporter v0.15.0 multi-target (/probe?target=...&auth_module=...) takes
# the credentials from an auth_modules config file, so that file necessarily holds
# plaintext passwords and is gitignored. Doppler project dhg-monitoring / config dev
# is the source of truth: one secret per instance, PG_DSN_<NAME>, holding a full DSN
# postgresql://user:password@host:5432/db?sslmode=disable
#
# The host/port/db half of each DSN is not secret and is duplicated as the scrape
# target in observability/prometheus/prometheus.yml (job postgres-multi); only the
# user/password half is consumed here.
#
#   ./observability/postgres-exporter/render-postgres-exporter.sh
#   docker compose up -d postgres-exporter-multi
#
# No secret value is ever echoed; the script prints module names only.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${SCRIPT_DIR}/postgres_exporter.yml"
PROJECT="dhg-monitoring"
CONFIG="dev"

# module name -> Doppler secret suffix. Module names match the auth_module query
# param in the prometheus.yml postgres-multi job.
MODULES=(medkb:MEDKB portage:PORTAGE eval:EVAL transcribe:TRANSCRIBE audio:AUDIO plane:PLANE)

command -v doppler >/dev/null || { echo "doppler CLI not found" >&2; exit 1; }

umask 077
tmp="$(mktemp "${OUT}.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

{
  echo "# GENERATED by render-postgres-exporter.sh — do not edit, do not commit."
  echo "# Source of truth: Doppler ${PROJECT}/${CONFIG}, secrets PG_DSN_*."
  echo "auth_modules:"
} >"$tmp"

for entry in "${MODULES[@]}"; do
  module="${entry%%:*}"
  secret="PG_DSN_${entry##*:}"
  dsn="$(doppler secrets get "$secret" --project "$PROJECT" --config "$CONFIG" --plain)"
  [ -n "$dsn" ] || { echo "empty secret $secret" >&2; exit 1; }

  # postgresql://USER:PASSWORD@host:port/db?...  -> USER, PASSWORD (percent-decoded)
  creds="${dsn#*://}"; creds="${creds%%@*}"
  user="${creds%%:*}"
  pass="${creds#*:}"
  [ -n "$user" ] && [ "$pass" != "$creds" ] || { echo "$secret is not a user:password DSN" >&2; exit 1; }

  {
    printf '  %s:\n' "$module"
    printf '    type: userpass\n'
    printf '    userpass:\n'
    printf '      username: %s\n' "$(printf '%s' "$user" | python3 -c 'import sys,urllib.parse,json;print(json.dumps(urllib.parse.unquote(sys.stdin.read())))')"
    printf '      password: %s\n' "$(printf '%s' "$pass" | python3 -c 'import sys,urllib.parse,json;print(json.dumps(urllib.parse.unquote(sys.stdin.read())))')"
    printf '    options:\n'
    printf '      sslmode: disable\n'
  } >>"$tmp"
  echo "rendered auth module: ${module}"
done

mv "$tmp" "$OUT"
chmod 600 "$OUT"
trap - EXIT
echo "wrote ${OUT} (${#MODULES[@]} auth modules)"
