// Predefined option lists for CME intake form fields.
// These mirror standard CME/ACCME taxonomy and eliminate free-text where possible.

export const HCP_CREDENTIAL_TYPES = [
  "Nurse Practitioner (NP)",
  "Physician (MD/DO)",
  "Physician Assistant (PA-C)",
];

// ABMS Member Boards + AMA-recognized specialties + Primary Care
// Source: American Board of Medical Specialties (ABMS) and AMA Physician Masterfile
export const THERAPEUTIC_AREAS = [
  "Allergy and Immunology",
  "Anesthesiology",
  "Cardiology",
  "Colon and Rectal Surgery",
  "Critical Care Medicine",
  "Dermatology",
  "Emergency Medicine",
  "Endocrinology, Diabetes and Metabolism",
  "Family Medicine",
  "Gastroenterology",
  "General Internal Medicine",
  "General Surgery",
  "Geriatric Medicine",
  "Gynecologic Oncology",
  "Hematology",
  "Hematology/Oncology",
  "Hospice and Palliative Medicine",
  "Infectious Disease",
  "Maternal-Fetal Medicine",
  "Medical Genetics and Genomics",
  "Medical Oncology",
  "Neonatal-Perinatal Medicine",
  "Nephrology",
  "Neurological Surgery",
  "Neurology",
  "Nuclear Medicine",
  "Obstetrics and Gynecology",
  "Ophthalmology",
  "Orthopaedic Surgery",
  "Otolaryngology – Head and Neck Surgery",
  "Pain Medicine",
  "Pathology",
  "Pediatrics",
  "Physical Medicine and Rehabilitation",
  "Physiology",
  "Plastic Surgery",
  "Preventive Medicine",
  "Primary Care",
  "Psychiatry",
  "Pulmonology",
  "Radiation Oncology",
  "Radiology",
  "Reproductive Endocrinology and Infertility",
  "Rheumatology",
  "Sleep Medicine",
  "Sports Medicine",
  "Thoracic Surgery",
  "Transplant Surgery",
  "Urology",
  "Vascular Surgery",
  "Other",
];

// Disease states with funding tier signal based on pharma revenue and CME grant activity.
// Sources: IQVIA Global Use of Medicines 2025, Evaluate World Preview 2025, ACCME 2024 Data Report.
// Tier: "high" = blockbuster drugs + heavy CME investment, "medium" = active products/growing pipeline,
// "low" = mostly generic/mature market or niche.
export type FundingTier = "high" | "medium" | "low";
export interface DiseaseStateOption {
  value: string;
  tier: FundingTier;
}

export const DISEASE_STATES: DiseaseStateOption[] = [
  // --- High Funding Likelihood ---
  // Major pharma investment, multiple active branded products, frequent CME grants
  { value: "Asthma", tier: "high" },
  { value: "Atopic Dermatitis / Eczema", tier: "high" },
  { value: "Atrial Fibrillation", tier: "high" },
  { value: "Breast Cancer", tier: "high" },
  { value: "Chronic Lymphocytic Leukemia (CLL)", tier: "high" },
  { value: "Chronic Obstructive Pulmonary Disease (COPD)", tier: "high" },
  { value: "Colorectal Cancer", tier: "high" },
  { value: "Crohn's Disease", tier: "high" },
  { value: "Heart Failure (HFpEF)", tier: "high" },
  { value: "Heart Failure (HFrEF)", tier: "high" },
  { value: "HIV/AIDS", tier: "high" },
  { value: "Hyperlipidemia / Dyslipidemia", tier: "high" },
  { value: "Lung Cancer (NSCLC)", tier: "high" },
  { value: "Major Depressive Disorder", tier: "high" },
  { value: "Melanoma", tier: "high" },
  { value: "Migraine", tier: "high" },
  { value: "Multiple Myeloma", tier: "high" },
  { value: "Multiple Sclerosis", tier: "high" },
  { value: "Non-Hodgkin Lymphoma", tier: "high" },
  { value: "Obesity", tier: "high" },
  { value: "Prostate Cancer", tier: "high" },
  { value: "Psoriasis", tier: "high" },
  { value: "Rheumatoid Arthritis", tier: "high" },
  { value: "Type 2 Diabetes Mellitus", tier: "high" },
  { value: "Ulcerative Colitis", tier: "high" },

  // --- Medium Funding Likelihood ---
  // Active products or growing pipeline, moderate CME grant volume
  { value: "Alzheimer's Disease / Dementia", tier: "medium" },
  { value: "Bipolar Disorder", tier: "medium" },
  { value: "Bladder Cancer", tier: "medium" },
  { value: "Chronic Kidney Disease", tier: "medium" },
  { value: "Coronary Artery Disease", tier: "medium" },
  { value: "Diabetic Kidney Disease", tier: "medium" },
  { value: "Epilepsy / Seizure Disorders", tier: "medium" },
  { value: "Hepatitis B", tier: "medium" },
  { value: "Hepatitis C", tier: "medium" },
  { value: "Hepatocellular Carcinoma", tier: "medium" },
  { value: "Hypertension", tier: "medium" },
  { value: "Idiopathic Pulmonary Fibrosis", tier: "medium" },
  { value: "Lung Cancer (SCLC)", tier: "medium" },
  { value: "NAFLD / NASH / MASLD", tier: "medium" },
  { value: "Ovarian Cancer", tier: "medium" },
  { value: "Pancreatic Cancer", tier: "medium" },
  { value: "Parkinson's Disease", tier: "medium" },
  { value: "Psoriatic Arthritis", tier: "medium" },
  { value: "Pulmonary Arterial Hypertension", tier: "medium" },
  { value: "Renal Cell Carcinoma", tier: "medium" },
  { value: "RSV Infection", tier: "medium" },
  { value: "Schizophrenia / Schizoaffective Disorder", tier: "medium" },
  { value: "Sickle Cell Disease", tier: "medium" },
  { value: "Systemic Lupus Erythematosus", tier: "medium" },
  { value: "Type 1 Diabetes Mellitus", tier: "medium" },
  { value: "Venous Thromboembolism (DVT/PE)", tier: "medium" },

  // --- Lower Funding Likelihood ---
  // Mostly generic/mature market, fewer new branded products, less commercial support
  { value: "Acute Coronary Syndrome", tier: "low" },
  { value: "COVID-19 / Respiratory Viral Infections", tier: "low" },
  { value: "Gout", tier: "low" },
  { value: "Inflammatory Bowel Disease (General)", tier: "low" },
  { value: "Osteoporosis", tier: "low" },
  { value: "Peripheral Artery Disease", tier: "low" },
  { value: "Other", tier: "low" },
];

// Target audiences — specialty/role-based only
// HCP credential types (MD/DO, NP, PA) are in the separate HCP Credential Types field
export const TARGET_AUDIENCES = [
  "Anesthesiologists",
  "Cardiologists",
  "Cardiothoracic Surgeons",
  "Clinical Nurse Specialists",
  "Clinical Pharmacists",
  "Colorectal Surgeons",
  "Dermatologists",
  "Emergency Medicine Physicians",
  "Endocrinologists",
  "Family Medicine Physicians",
  "Gastroenterologists",
  "General Surgeons",
  "Geriatricians",
  "Gynecologic Oncologists",
  "Hematologists",
  "Hospitalists",
  "Immunologists",
  "Infectious Disease Specialists",
  "Internists",
  "Medical Directors",
  "Medical Students",
  "Nephrologists",
  "Neurologists",
  "Neurosurgeons",
  "Obstetricians/Gynecologists",
  "Oncologists",
  "Ophthalmologists",
  "Oral and Maxillofacial Surgeons",
  "Orthopaedic Surgeons",
  "Otolaryngologists (ENT)",
  "Pain Medicine Specialists",
  "Palliative Care Specialists",
  "Pathologists",
  "Pediatric Surgeons",
  "Pediatricians",
  "Physiatrists (PM&R)",
  "Plastic Surgeons",
  "Primary Care Physicians",
  "Psychiatrists",
  "Pulmonologists",
  "Quality/Safety Officers",
  "Radiologists",
  "Residents/Fellows",
  "Rheumatologists",
  "Sports Medicine Physicians",
  "Surgical Oncologists",
  "Transplant Surgeons",
  "Trauma Surgeons",
  "Urologists",
  "Vascular Surgeons",
];

export const LEARNING_FORMATS = [
  "Live Webinar",
  "Enduring Material (Online)",
  "Enduring Material (Print)",
  "Live In-Person Conference",
  "Live In-Person Workshop",
  "Blended Learning",
  "Case-Based Learning",
  "Simulation-Based",
  "Performance Improvement (PI)",
  "Internet Point-of-Care",
  "Journal-Based CME",
  "Regularly Scheduled Series (RSS)",
  "Test Item Writing",
  "Committee Learning",
];

export const TREATMENT_MODALITIES = [
  "Pharmacotherapy",
  "Immunotherapy",
  "Targeted Therapy",
  "Chemotherapy",
  "Radiation Therapy",
  "Surgical Intervention",
  "Minimally Invasive Procedures",
  "Device Therapy",
  "Gene Therapy",
  "Cell Therapy",
  "Biologics",
  "Biosimilars",
  "Combination Therapy",
  "Supportive/Palliative Care",
  "Behavioral/Lifestyle Intervention",
  "Physical/Occupational Therapy",
  "Diagnostic Imaging",
  "Laboratory Diagnostics",
  "Screening/Prevention",
  "Monitoring/Surveillance",
];

export const PATIENT_POPULATIONS = [
  "Adults (18-64)",
  "Older Adults (65+)",
  "Geriatric (75+)",
  "Pediatric (0-17)",
  "Neonatal/Infant (0-1)",
  "Adolescent (12-17)",
  "Women of Childbearing Age",
  "Pregnant/Lactating Women",
  "Men",
  "Women",
  "Racial/Ethnic Minorities",
  "Underserved Populations",
  "Rural Populations",
  "LGBTQ+",
  "Immunocompromised",
  "Transplant Recipients",
  "Chronic Disease Patients",
  "Newly Diagnosed",
  "Treatment-Experienced",
  "Treatment-Naive",
  "Clinical Trial Participants",
];

export const DISEASE_STAGES = [
  "Prevention/Screening",
  "Pre-clinical/At Risk",
  "Early Stage (Stage I)",
  "Early Stage (Stage II)",
  "Locally Advanced (Stage III)",
  "Advanced/Metastatic (Stage IV)",
  "Recurrent/Relapsed",
  "Refractory/Resistant",
  "Acute",
  "Subacute",
  "Chronic/Stable",
  "Progressive",
  "End-Stage",
  "Remission",
  "Mild",
  "Moderate",
  "Severe",
  "NYHA Class I",
  "NYHA Class II",
  "NYHA Class III",
  "NYHA Class IV",
  "All Stages",
];

export const COMMON_COMORBIDITIES = [
  "Type 2 Diabetes Mellitus",
  "Type 1 Diabetes Mellitus",
  "Hypertension",
  "Hyperlipidemia/Dyslipidemia",
  "Obesity (BMI ≥30)",
  "Chronic Kidney Disease (CKD)",
  "Heart Failure (HFrEF)",
  "Heart Failure (HFpEF)",
  "Atrial Fibrillation",
  "Coronary Artery Disease",
  "Peripheral Artery Disease",
  "Stroke/TIA",
  "COPD",
  "Asthma",
  "Chronic Liver Disease",
  "NAFLD/NASH",
  "Depression/Anxiety",
  "Chronic Pain",
  "Osteoporosis",
  "Autoimmune Disorders",
  "HIV/AIDS",
  "Hepatitis B/C",
  "Venous Thromboembolism",
  "Sleep Apnea",
  "Substance Use Disorders",
];

export const GAP_EVIDENCE_SOURCES = [
  "Published Literature/Meta-analyses",
  "Clinical Practice Guidelines",
  "Needs Assessment Surveys",
  "Claims/Administrative Data",
  "Electronic Health Records (EHR)",
  "Quality Measures/HEDIS Data",
  "CMS/Payer Reports",
  "Expert Faculty Input",
  "Learner Pre-test/Post-test Data",
  "Previous CME Outcomes Data",
  "Patient Outcomes Registry",
  "FDA Safety Communications",
  "Professional Society Reports",
  "CDC/WHO Surveillance Data",
  "Institutional Quality Reports",
  "Focus Groups/Interviews",
];

export const MEASUREMENT_APPROACHES = [
  "Pre/Post Knowledge Assessment",
  "Pre/Post Competence Assessment",
  "Intention-to-Change Survey",
  "Commitment-to-Change (CTC)",
  "Self-Reported Practice Change (30-day)",
  "Self-Reported Practice Change (60-day)",
  "Self-Reported Practice Change (90-day)",
  "Chart Audit/EHR Review",
  "Claims Data Analysis",
  "Patient Outcomes Measurement",
  "Quality Metrics Tracking",
  "Simulation Performance Assessment",
  "Objective Structured Clinical Exam (OSCE)",
  "360-Degree Evaluation",
  "Direct Observation",
  "Case-Based Assessment",
];

export const FOLLOW_UP_TIMELINES = [
  "Immediate Post-Activity Only",
  "30 Days",
  "60 Days",
  "90 Days",
  "30 and 60 Days",
  "30, 60, and 90 Days",
  "6 Months",
  "12 Months",
  "18 Months",
  "24 Months",
];

export const DISTRIBUTION_CHANNELS = [
  "Web (Desktop)",
  "Mobile App",
  "Email Campaign",
  "Social Media (LinkedIn)",
  "Social Media (Twitter/X)",
  "Social Media (Facebook)",
  "Professional Society Website",
  "Medical Journal",
  "Conference/Meeting",
  "Hospital/Health System Intranet",
  "Learning Management System (LMS)",
  "Podcast",
  "Webinar Platform",
  "Print Mailing",
  "Point-of-Care Platform",
  "EHR Integration",
];

export const GEO_REGIONS = [
  "United States",
  "Canada",
  "United States & Canada",
  "North America",
  "European Union",
  "United Kingdom",
  "Europe (All)",
  "Asia-Pacific",
  "Japan",
  "China",
  "Latin America",
  "Middle East & Africa",
  "Australia/New Zealand",
  "Global (No Restrictions)",
];

export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Portuguese",
  "Italian",
  "Mandarin Chinese",
  "Japanese",
  "Korean",
  "Arabic",
  "Hindi",
  "Russian",
];

export const REGULATORY_CONSIDERATIONS = [
  "FDA-Approved Indications Only",
  "Off-Label Use Discussion Required",
  "Investigational Agents Included",
  "REMS Program Compliance",
  "Controlled Substance Prescribing (DEA)",
  "Black Box Warning Coverage",
  "Biosimilar Interchangeability",
  "Drug-Drug Interaction Focus",
  "Pregnancy/Lactation Labeling",
  "Pediatric Use Considerations",
  "Geriatric Use Considerations",
  "Renal/Hepatic Dosing Adjustments",
  "None",
];
