#!/usr/bin/env bash
# Render services/medkb/.env.otel — the OTLP export config that points medkb's
# OpenTelemetry tracer at Langfuse (Tempo retired 2026-09-04, decision D-A).
#
# The Langfuse project keys are credentials, so the rendered file is gitignored
# (mode 600) and read by docker-compose.yml as an optional env_file. Re-run
# after minting or rotating the keys, then restart medkb:
#
#   observability/scripts/render-medkb-otel-env.sh
#   docker compose up -d dhg-medkb-api
#
# If LANGFUSE_AIFACTORY_PUBLIC_KEY / LANGFUSE_AIFACTORY_SECRET_KEY are not in
# Doppler (dhg-monitoring/dev) the script removes any stale .env.otel, warns,
# and exits 0 — medkb then starts with tracing disabled.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$REPO/services/medkb/.env.otel"

LANGFUSE_OTLP_ENDPOINT="http://10.0.0.179:3000/api/public/otel"

# Never echoed; only ever written into the gitignored $OUT.
PUB="$(doppler secrets get LANGFUSE_AIFACTORY_PUBLIC_KEY \
  --project dhg-monitoring --config dev --plain 2>/dev/null || true)"
SEC="$(doppler secrets get LANGFUSE_AIFACTORY_SECRET_KEY \
  --project dhg-monitoring --config dev --plain 2>/dev/null || true)"

if [ -z "$PUB" ] || [ -z "$SEC" ]; then
  rm -f "$OUT"
  echo "WARN: LANGFUSE_AIFACTORY_* not in Doppler; medkb OTLP export not configured"
  exit 0
fi

AUTH="$(printf '%s:%s' "$PUB" "$SEC" | base64 -w0)"

umask 077
cat > "$OUT" <<EOF
# Generated by observability/scripts/render-medkb-otel-env.sh — do not edit.
OTEL_ENDPOINT=$LANGFUSE_OTLP_ENDPOINT
OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic $AUTH
OTEL_SERVICE_NAME=dhg-medkb
EOF
chmod 600 "$OUT"

echo "Rendered $OUT (mode 600) -> $LANGFUSE_OTLP_ENDPOINT"
